// <auto-generated />
namespace eForge.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class addedLinkText : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedLinkText));
        
        string IMigrationMetadata.Id
        {
            get { return "201408150018351_added LinkText"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
